version: '3'
services:
    db:
      image: postgres:16-alpine3.20
      container_name: pgrest-db-container
      restart: unless-stopped    
      ports:
        - "5432:5432"
      expose:
        - "5432"    
      environment:
        - POSTGRES_DB=postgres_db
        - POSTGRES_USER=postgres_user
        - POSTGRES_PASSWORD=8Fny?aXEFkh9ePA3
      volumes:
        - "./postgres-data:/var/lib/postgresql/data"
        - "./initdb:/docker-entrypoint-initdb.d"
      networks:
        - my-demo-network

volumes:
  postgres-data:

networks:
  my-demo-network:
    driver: bridge