version: '3'
services:
    db:
      image: postgres:16-alpine3.20
      container_name: pgrest-db-container
      restart: unless-stopped    
      ports:
        - "5432:5432"
      expose:
        - "5432"    
      environment:
        - POSTGRES_DB=postgres_db
        - POSTGRES_USER=postgres_user
        - POSTGRES_PASSWORD=8Fny?aXEFkh9ePA3
      volumes:
        - "./postgres-data:/var/lib/postgresql/data"
        - "./initdb:/docker-entrypoint-initdb.d"
      networks:
        - my-demo-network

    server:
      image: postgrest/postgrest:v12.2.8
      container_name: pgrest-server
      ports:
        - "3000:3000"
      expose:
        - "3000"
      links:
        - db:db
      environment:
        - PGRST_DB_URI=postgres://authenticator:8Fny?aXEFkh9ePA3@db:5432/postgres_db
        - PGRST_DB_SCHEMA=api
        - PGRST_DB_ANON_ROLE=api_anon      
      depends_on:
        - db
      networks:
        - my-demo-network
      restart: unless-stopped

volumes:
  postgres-data:

networks:
  my-demo-network:
    driver: bridge