global:
  scrape_interval: 15s
  evaluation_interval: 120s

rule_files:
  # - "alert.rules"
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['db:5432']

  - job_name: 'postgrest'
    static_configs:
      - targets: ['server:3000']
