global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['db:5432']

  - job_name: 'postgrest'
    static_configs:
      - targets: ['server:3000']
